### ISSUE TITLE
`AttributeError` when resolving `install --strip-program`

### ISSUE THREAD

**Issue by Jayman2000** [abathur/resholve#100]
Trying to run `nix-build` on this will cause an `AttributeError`:

```nix
# 🅭🄍1.0 This file is dedicated to the public domain using the CC0 1.0 Universal
# Public Domain Dedication <https://creativecommons.org/publicdomain/zero/1.0/>.
with import <nixpkgs> { };

resholve.writeScript "example"
{
  inputs = [
    coreutils
    hello
  ];
  interpreter = "${bash}/bin/bash";
} ''
  install --strip-program hello
''
```

Here’s the log:

```none
[resholve context] : invoking resholve with PWD=/build
[resholve context] RESHOLVE_LORE=/nix/store/qycl2ldxhk6mzamv56v6bz115szhbqq2-more-binlore
[resholve context] RESHOLVE_INPUTS=/nix/store/j4fwy5gi1rdlrlbk2c0vnbs7fmlm60a7-coreutils-9.1/bin:/nix/store/ibpsas4imhv84qmdk5ffh51y0ayrqa94-hello-2.12.1/bin
[resholve context] RESHOLVE_INTERPRETER=/nix/store/8fv91097mbh5049i9rglc73dx6kjg3qk-bash-5.2-p15/bin/bash
[resholve context] /nix/store/flhjs88iz0mczaw3qifci7smxx1gaq0y-resholve-0.9.0/bin/resholve --overwrite /nix/store/vr71qlkky81v2kh1jb0g6cn2j2vmdpgg-example
Traceback (most recent call last):
  File "/nix/store/flhjs88iz0mczaw3qifci7smxx1gaq0y-resholve-0.9.0/bin/.resholve-wrapped", line 4714, in <module>
    sys.exit(punshow())
  File "/nix/store/flhjs88iz0mczaw3qifci7smxx1gaq0y-resholve-0.9.0/bin/.resholve-wrapped", line 946, in punshow
    resolve_cmdlikes()
  File "/nix/store/flhjs88iz0mczaw3qifci7smxx1gaq0y-resholve-0.9.0/bin/.resholve-wrapped", line 3085, in resolve_cmdlikes
    cmdlike.resolve()
  File "/nix/store/flhjs88iz0mczaw3qifci7smxx1gaq0y-resholve-0.9.0/bin/.resholve-wrapped", line 3057, in resolve
    self._resolve_invocations(solution)
  File "/nix/store/flhjs88iz0mczaw3qifci7smxx1gaq0y-resholve-0.9.0/bin/.resholve-wrapped", line 3016, in _resolve_invocations
    source.look_for_external_sub_execution(self.name, invocation)
  File "/nix/store/flhjs88iz0mczaw3qifci7smxx1gaq0y-resholve-0.9.0/bin/.resholve-wrapped", line 3986, in look_for_external_sub_execution
    parsed = parser.parse_known_args(invocation.args)
  File "/nix/store/r3qy746fdmdx402xy6x1ymn0n8rx013a-python-2.7.18.6/lib/python2.7/argparse.py", line 1737, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/nix/store/r3qy746fdmdx402xy6x1ymn0n8rx013a-python-2.7.18.6/lib/python2.7/argparse.py", line 1943, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/nix/store/r3qy746fdmdx402xy6x1ymn0n8rx013a-python-2.7.18.6/lib/python2.7/argparse.py", line 1883, in consume_optional
    take_action(action, args, option_string)
  File "/nix/store/r3qy746fdmdx402xy6x1ymn0n8rx013a-python-2.7.18.6/lib/python2.7/argparse.py", line 1811, in take_action
    action(self, namespace, argument_values, option_string)
  File "/nix/store/flhjs88iz0mczaw3qifci7smxx1gaq0y-resholve-0.9.0/bin/.resholve-wrapped", line 372, in __call__
    Invocation(words=values),
  File "/nix/store/flhjs88iz0mczaw3qifci7smxx1gaq0y-resholve-0.9.0/bin/.resholve-wrapped", line 3314, in __new__
    self.first_spid = firstword.first_spid
AttributeError: 'str' object has no attribute 'first_spid'
```

**Comment by abathur** [comment]
Thanks for catching these. I'll hold off on cutting a release until you can confirm the fixes.

**Comment by Jayman2000** [comment]
> I'll hold off on cutting a release until you can confirm the fixes.

I can confirm that #100 and #101 are fixed. To help me test the fixes, I made [this script](https://gist.github.com/Jayman2000/ce37d68f49789b3d46659c8da6401179). It allows me to do this:

```console
$ ./ez-resholve.sh script-that-uses-install.sh coreutils hello`
```

instead of having to build the lore and set all of the `RESHOLVE_` variables manually.
