### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'dfas'

### ISSUE THREAD

**Issue by D3vil0p3r** [abathur/resholve#114]
I'm trying to use resholve for [lbd](https://github.com/D3vil0p3r/lbd/blob/main/lbd) script. When I launch `resholve ./lbd --interpreter none --path ""`, I get the error:
```
Traceback (most recent call last):
  File "/nix/store/26713f1xjvqcsmf01051mj50n2myppwk-resholve-0.9.0/bin/.resholve-wrapped", line 4714, in <module>
    sys.exit(punshow())
  File "/nix/store/26713f1xjvqcsmf01051mj50n2myppwk-resholve-0.9.0/bin/.resholve-wrapped", line 942, in punshow
    epilogue=args.epilogue,
  File "/nix/store/26713f1xjvqcsmf01051mj50n2myppwk-resholve-0.9.0/bin/.resholve-wrapped", line 738, in resolve_script
    script_path, shebang=shebang, prologue=prologue, epilogue=epilogue
  File "/nix/store/26713f1xjvqcsmf01051mj50n2myppwk-resholve-0.9.0/bin/.resholve-wrapped", line 4208, in __init__
    node = self.parse_script(script, script_path)
  File "/nix/store/26713f1xjvqcsmf01051mj50n2myppwk-resholve-0.9.0/bin/.resholve-wrapped", line 4275, in parse_script
    self._make_parser(parse_ctx, script, arena)
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/core/main_loop.py", line 356, in ParseWholeFile
    node = c_parser.ParseLogicalLine()  # can raise ParseError
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/osh/cmd_parse.py", line 2369, in ParseLogicalLine
    node = self._ParseCommandLine()
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/osh/cmd_parse.py", line 2228, in _ParseCommandLine
    child = self.ParseAndOr()
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/osh/cmd_parse.py", line 2147, in ParseAndOr
    return self._ParseAndOr()
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/osh/cmd_parse.py", line 2158, in _ParseAndOr
    child = self.ParsePipeline()
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/osh/cmd_parse.py", line 2090, in ParsePipeline
    child = self.ParseCommand()
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/osh/cmd_parse.py", line 2013, in ParseCommand
    return self.ParseCompoundCommand()
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/osh/cmd_parse.py", line 1680, in ParseCompoundCommand
    return self.ParseFor()
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/osh/cmd_parse.py", line 1305, in ParseFor
    n1 = self._ParseForExprLoop()
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/osh/cmd_parse.py", line 1190, in _ParseForExprLoop
    node.body = self.ParseDoGroup()
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/osh/cmd_parse.py", line 1120, in ParseDoGroup
    c_list = self._ParseCommandList()  # could be any thing
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/osh/cmd_parse.py", line 2352, in _ParseCommandList
    node = self._ParseCommandTerm()
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/osh/cmd_parse.py", line 2291, in _ParseCommandTerm
    child = self.ParseAndOr()
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/osh/cmd_parse.py", line 2147, in ParseAndOr
    return self._ParseAndOr()
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/osh/cmd_parse.py", line 2158, in _ParseAndOr
    child = self.ParsePipeline()
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/osh/cmd_parse.py", line 2090, in ParsePipeline
    child = self.ParseCommand()
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/osh/cmd_parse.py", line 2013, in ParseCommand
    return self.ParseCompoundCommand()
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/osh/cmd_parse.py", line 1688, in ParseCompoundCommand
    n4 = self.ParseIf()
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/osh/cmd_parse.py", line 1608, in ParseIf
    commands = self._ParseCommandList()
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/osh/cmd_parse.py", line 2352, in _ParseCommandList
    node = self._ParseCommandTerm()
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/osh/cmd_parse.py", line 2291, in _ParseCommandTerm
    child = self.ParseAndOr()
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/osh/cmd_parse.py", line 2147, in ParseAndOr
    return self._ParseAndOr()
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/osh/cmd_parse.py", line 2158, in _ParseAndOr
    child = self.ParsePipeline()
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/osh/cmd_parse.py", line 2090, in ParsePipeline
    child = self.ParseCommand()
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/osh/cmd_parse.py", line 2064, in ParseCommand
    return self.ParseSimpleCommand()
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/osh/cmd_parse.py", line 980, in ParseSimpleCommand
    redirects, words, typed_args, block = self._ScanSimpleCommand()
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/osh/cmd_parse.py", line 681, in _ScanSimpleCommand
    self._Peek()
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/osh/cmd_parse.py", line 544, in _Peek
    w = self.w_parser.ReadWord(self.next_lex_mode)
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/osh/word_parse.py", line 1820, in ReadWord
    w, need_more = self._ReadWord(lex_mode)
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/osh/word_parse.py", line 1739, in _ReadWord
    w = self._ReadCompoundWord(lex_mode)
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/osh/word_parse.py", line 1472, in _ReadCompoundWord
    return self._ReadCompoundWord3(lex_mode, Id.Undefined_Tok, True)
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/osh/word_parse.py", line 1565, in _ReadCompoundWord3
    part = self._ReadUnquotedLeftParts(try_triple_quote, triple_out)
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/osh/word_parse.py", line 753, in _ReadUnquotedLeftParts
    return self._ReadExprSub(lex_mode_e.ShCommand)
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/osh/word_parse.py", line 1034, in _ReadExprSub
    enode, _ = self.parse_ctx.ParseOilExpr(self.lexer, grammar_nt.oil_expr_sub)
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/frontend/parse_lib.py", line 376, in ParseOilExpr
    pnode, last_token = self._ParseOil(lx, start_symbol)
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/frontend/parse_lib.py", line 329, in _ParseOil
    return e_parser.Parse(lexer, start_symbol)
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/oil_lang/expr_parse.py", line 322, in Parse
    self.push_parser.setup(start_symbol)
  File "/nix/store/rjcf7yilll8xv4z9i8iv4wvlamm1cmwx-python2.7-oildev-unstable-2021-07-14/lib/python2.7/site-packages/oil/pgen2/parse.py", line 111, in setup
    self.stack = [_StackItem(self.grammar.dfas[start], 0, newnode)]
AttributeError: 'NoneType' object has no attribute 'dfas'
```
According to some tests, it seems that the error could be caused by:
(line 78)
```bash
 if [ $[ $D1 * 3600 + $D2 * 60 + $D3 ] -lt $D4 ]
 then
  echo "FOUND"
  METHODS="$METHODS HTTP[Date]"
  break;
 fi

 D4="$[ $D1 * 3600 + $D2 * 60 + $D3 ]"
 if [ $i -eq $[$QUERIES - 1] ]
 then
  echo "NOT FOUND" 
 fi
```
(line 98)
```bash
 if ! cmp .log .nlog &>/dev/null && [ -e .log ]
 then
  echo "FOUND"
  diff .log .nlog | grep -e ">" -e "<"
  METHODS="$METHODS HTTP[Diff]"
  break;
 fi

 cp .nlog .log

 if [ $i -eq $[$QUERIES - 1] ]
 then
  echo "NOT FOUND" 
 fi
 ```
 For example, the usage of `$[$QUERIES - 1]` makes resholve to crash.

**Comment by abathur** [comment]
I'm not sure I'll have access to a computer today to poke at this, but if you have a little time a good place to start is with seeing if oil's osh shell can parse it.

You can just try the one in nixpkgs. I think maybe like `nix-shell -p oil --command "osh -n lbd"` might work.

If that works, it's possible this is something oil's alresdy caught and fixed in the meantime. If not, we may need to figure out where it's going awry in order to check upstream for a matching issue or open our own. (if there's already one open, it may also have a recommended workaround and some notes on whether this is a quick fix or not.)

**Comment by D3vil0p3r** [comment]
The output of that command is:
```
   if [ $[ $D1 * 3600 + $D2 * 60 + $D3 ] -lt $D4 ]
           ^~~
lbd:78: In expressions, remove $ and use `D1`, or sometimes "$D1"
```

**Comment by abathur** [comment]
Sounds like maybe its a wontfix parse issue with a preferred workaround thst is now being correctly caught/messaged in newer osh versions. 

Can you try to get that workaround working against osh and then see if it'll run through resholve?

**Comment by D3vil0p3r** [comment]
I applied the suggested workaround and then I get a long output containing something like:
```
(command.CommandList
  children: [
    (command.ShAssignment
      left: <Id.Lit_VarLike 'QUERIES='>
      pairs: [
        (AssignPair
          left: <Id.Lit_VarLike 'QUERIES='>
          lhs: (sh_lhs_expr.Name left:<Id.Lit_VarLike 'QUERIES='> name:QUERIES)
          op: assign_op.Equal
          rhs: {<50>}
        )
      ]
      redirects: []
    )
    (command.ShAssignment
      left: <Id.Lit_VarLike 'DOMAIN='>
      pairs: [
        (AssignPair
          left: <Id.Lit_VarLike 'DOMAIN='>
          lhs: (sh_lhs_expr.Name left:<Id.Lit_VarLike 'DOMAIN='> name:DOMAIN)
          op: assign_op.Equal
          rhs: {($ Id.VSub_Number 1)}
        )
      ]
      redirects: []
    )
    ....
    ```
    but when I run again `resholve ./lbd --interpreter none --path ""`, I still get the error of the first post.

**Comment by abathur** [comment]
Ok. The long output is just a parse tree (good sign), so maybe there's an actual fix we'll need.

I'll take a look at updating the version resholve uses. Sometimes these are quick and trivial, and sometimes they mean a bit of testing and refactoring. Won't know about timeline until I get my hands dirty.

**Comment by abathur** [comment]
I think I have updates to 0.20.0 worked out and pushed to https://github.com/abathur/resholve/tree/update_oil (current head: https://github.com/abathur/resholve/commit/05b25cef96136a3b88a97ae92812037c9ddfcea5). 

Can you confirm whether this works on your script?

**Comment by abathur** [comment]
Got a chance to play with this today and was able to confirm that the parser update _alone_ wasn't enough to fix this (I think resholve was still slightly mishandling the upstream API).

I'll try to remember to comment when a release with this fix is in nixpkgs.
