### ISSUE TITLE
AttributeError: 'str' object has no attribute 'first_spid'

### ISSUE THREAD

**Issue by cole-h** [abathur/resholve#70]
When updating Nixpkgs recently, some CI caught this issue with one of our resholved scripts:

```
    Traceback (most recent call last):
      File "/nix/store/33xkmpzvw86kyv564lp0xinjjxnn471m-resholve-0.6.6/bin/.resholve-wrapped", line 4478, in <module>
        sys.exit(punshow())
      File "/nix/store/33xkmpzvw86kyv564lp0xinjjxnn471m-resholve-0.6.6/bin/.resholve-wrapped", line 903, in punshow
        resolve_cmdlikes()
      File "/nix/store/33xkmpzvw86kyv564lp0xinjjxnn471m-resholve-0.6.6/bin/.resholve-wrapped", line 2902, in resolve_cmdlikes
        cmdlike.resolve()
      File "/nix/store/33xkmpzvw86kyv564lp0xinjjxnn471m-resholve-0.6.6/bin/.resholve-wrapped", line 2874, in resolve
        self._resolve_invocations(solution)
      File "/nix/store/33xkmpzvw86kyv564lp0xinjjxnn471m-resholve-0.6.6/bin/.resholve-wrapped", line 2840, in _resolve_invocations
        source.look_for_external_sub_execution(self.name, invocation)
      File "/nix/store/33xkmpzvw86kyv564lp0xinjjxnn471m-resholve-0.6.6/bin/.resholve-wrapped", line 3775, in look_for_external_sub_execution
        parsed = parser.parse_known_args(invocation.args)
      File "/nix/store/w05yrq8d41vbd7cz3gyq3ysidz2qyfdp-python-2.7.18/lib/python2.7/argparse.py", line 1737, in parse_known_args
        namespace, args = self._parse_known_args(args, namespace)
      File "/nix/store/w05yrq8d41vbd7cz3gyq3ysidz2qyfdp-python-2.7.18/lib/python2.7/argparse.py", line 1943, in _parse_known_args
        start_index = consume_optional(start_index)
      File "/nix/store/w05yrq8d41vbd7cz3gyq3ysidz2qyfdp-python-2.7.18/lib/python2.7/argparse.py", line 1883, in consume_optional
        take_action(action, args, option_string)
      File "/nix/store/w05yrq8d41vbd7cz3gyq3ysidz2qyfdp-python-2.7.18/lib/python2.7/argparse.py", line 1811, in take_action
        action(self, namespace, argument_values, option_string)
      File "/nix/store/33xkmpzvw86kyv564lp0xinjjxnn471m-resholve-0.6.6/bin/.resholve-wrapped", line 339, in __call__
        Invocation(words=values),
      File "/nix/store/33xkmpzvw86kyv564lp0xinjjxnn471m-resholve-0.6.6/bin/.resholve-wrapped", line 3131, in __new__
        self.first_spid = firstword.first_spid
    AttributeError: 'str' object has no attribute 'first_spid'
```

It only appeared for this one script. I'll gladly send you said script (and the Nix expression), just reach out to me on Matrix when you have time.

**Comment by abathur** [comment]
I think I have had a fix for this, but I got distracted by some documentation work and didn't cut a release. 

I've now released v0.6.7 and opened NixOS/nixpkgs#145577 if you can confirm either of those work :)

**Comment by cole-h** [comment]
Sadly, that didn't appear to work. Same trace, different version :(

```
Traceback (most recent call last):
  File "/nix/store/lv77mh62aqm82g1k78gc4wvzy4bbx6wy-resholve-0.6.7/bin/.resholve-wrapped", line 4515, in <module>
    sys.exit(punshow())
  File "/nix/store/lv77mh62aqm82g1k78gc4wvzy4bbx6wy-resholve-0.6.7/bin/.resholve-wrapped", line 903, in punshow
    resolve_cmdlikes()
  File "/nix/store/lv77mh62aqm82g1k78gc4wvzy4bbx6wy-resholve-0.6.7/bin/.resholve-wrapped", line 2921, in resolve_cmdlikes
    cmdlike.resolve()
  File "/nix/store/lv77mh62aqm82g1k78gc4wvzy4bbx6wy-resholve-0.6.7/bin/.resholve-wrapped", line 2893, in resolve
    self._resolve_invocations(solution)
  File "/nix/store/lv77mh62aqm82g1k78gc4wvzy4bbx6wy-resholve-0.6.7/bin/.resholve-wrapped", line 2859, in _resolve_invocations
    source.look_for_external_sub_execution(self.name, invocation)
  File "/nix/store/lv77mh62aqm82g1k78gc4wvzy4bbx6wy-resholve-0.6.7/bin/.resholve-wrapped", line 3812, in look_for_external_sub_execution
    parsed = parser.parse_known_args(invocation.args)
  File "/nix/store/w05yrq8d41vbd7cz3gyq3ysidz2qyfdp-python-2.7.18/lib/python2.7/argparse.py", line 1737, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/nix/store/w05yrq8d41vbd7cz3gyq3ysidz2qyfdp-python-2.7.18/lib/python2.7/argparse.py", line 1943, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/nix/store/w05yrq8d41vbd7cz3gyq3ysidz2qyfdp-python-2.7.18/lib/python2.7/argparse.py", line 1883, in consume_optional
    take_action(action, args, option_string)
  File "/nix/store/w05yrq8d41vbd7cz3gyq3ysidz2qyfdp-python-2.7.18/lib/python2.7/argparse.py", line 1811, in take_action
    action(self, namespace, argument_values, option_string)
  File "/nix/store/lv77mh62aqm82g1k78gc4wvzy4bbx6wy-resholve-0.6.7/bin/.resholve-wrapped", line 339, in __call__
    Invocation(words=values),
  File "/nix/store/lv77mh62aqm82g1k78gc4wvzy4bbx6wy-resholve-0.6.7/bin/.resholve-wrapped", line 3150, in __new__
    self.first_spid = firstword.first_spid
AttributeError: 'str' object has no attribute 'first_spid'
```

**Comment by abathur** [comment]
v0.6.8 here and nixos/nixpgks#145586 will hopefully actually have this, now :)

**Comment by cole-h** [comment]
Confirmed fixed! Thanks!
